### ISSUE TITLE
Change CI publish mechanism

### ISSUE THREAD

**Issue by callumlocke** [ft-interactive/g-deploy#15]
Follow this (but adapt for v2): https://circleci.com/docs/1.0/npm-continuous-deployment/

**Comment by callumlocke** [comment]
from @aendrew on Slack: "The `tag` predicate in circle.yml doesn't work in 2.0 AFAICT."

...so we may need to keep using the 'check npm and publish if local version is newer' approach. but I still want to adopt the npm token approach detailed in the above guide.

**Comment by aendrew** [comment]
Tags actually work on Circle v2.

![download](https://user-images.githubusercontent.com/185041/46812838-7867d480-cd6d-11e8-8a54-3a3b4cb5a2f8.jpeg)
