### ISSUE TITLE
Make override path an array of strings

### ISSUE THREAD

**Issue by joannaskao** [ft-interactive/g-deploy#23]
This would allow us to pass in multiple paths (e.g. a case where we want an SVG to be both timestamped and at one persistent key).

https://github.com/ft-interactive/g-deploy/blob/master/src/Deployer.ts#L144

**Comment by aendrew** [comment]
I'd argue this violates the principle of least astonishment as a `path` argument implies a single string, and this is already a somewhat-dangerous feature to add, which means its use should be as simple and obvious as possible. Plus `Deployer` can already just be instantiated multiple times if it needs to be deployed to more than one custom S3 prefix.

Closing for now; if there's functionality needed that cannot be accomplished from multiple instantiations of `Deployer` will reopen.
